package profiles

import "testing"

func TestResolveSupportsDoolSourceLanguages(t *testing.T) {
	languages := []string{
		"TEXT",
		"C",
		"C89",
		"C99",
		"C11",
		"C17",
		"C18",
		"C23",
		"CPP",
		"CPP03",
		"CPP11",
		"CPP14",
		"CPP17",
		"CPP20",
		"CPP23",
		"CPP26",
		"PYTHON3",
		"PYPY3",
		"JAVA",
		"JAVA8",
		"JAVA11",
		"JAVA15",
		"JAVA17",
		"JAVA21",
		"GROOVY",
		"JAVASCRIPT",
		"TYPESCRIPT",
		"GO",
		"ZIG",
		"SCHEME",
		"AWK",
		"TCL",
		"GDL",
		"OCTAVE",
		"VHDL",
		"VERILOG",
		"SYSTEMVERILOG",
		"CRYSTAL",
		"VALA",
		"VLANG",
		"ODIN",
		"C3",
		"HARE",
		"VBNET",
		"VB",
		"GLEAM",
		"CUDA_OCELOT",
		"CARBON",
		"GRAPHQL",
		"ROCQ",
		"LEAN4",
		"LEAN",
		"AGDA",
		"DAFNY",
		"TLA",
		"TLAPLUS",
		"WHY3",
		"WHYML",
		"ISABELLE",
		"RUST",
		"RUST2015",
		"RUST2018",
		"RUST2021",
		"RUST2024",
		"KOTLIN",
		"COBOL",
		"GNUCOBOL",
		"CYTHON",
		"FORTRAN",
		"D",
		"OBJC",
		"OBJECTIVE_C",
		"OBJCPP",
		"OBJECTIVE_CPP",
		"COQ",
		"HASKELL",
		"SML",
		"HAXE",
		"LISP",
		"ASM",
		"AHEUI",
		"NASM",
		"SWIFT",
		"SQLITE",
		"JULIA",
		"RAKU",
		"ERLANG",
		"MERCURY",
		"PROLOG",
		"SCALA",
		"FSHARP",
		"WHITESPACE",
		"BF",
		"WASM",
		"OCAML",
		"ELIXIR",
		"COFFEESCRIPT",
		"RUBY",
		"PHP",
		"CSHARP",
		"R",
		"LUA",
		"PERL",
		"VB6",
		"FREEBASIC",
		"CLASSIC_BASIC",
		"QBASIC",
		"SMALLTALK",
		"GST",
		"GOLFSCRIPT",
		"MOJO",
		"DENO",
		"KOTLIN_JVM",
		"KOTLIN_JVM8",
		"KOTLIN_JVM11",
		"KOTLIN_JVM17",
		"KOTLIN_JVM21",
		"KOTLIN_JAVA",
		"KOTLIN_JAVA8",
		"KOTLIN_JAVA11",
		"KOTLIN_JAVA17",
		"KOTLIN_JAVA21",
		"DUCKDB",
		"BQN",
		"APL",
		"GNU_APL",
		"UIUA",
		"JANET",
		"SED",
		"BC",
		"FORTH",
		"GFORTH",
		"UHMLANG",
	}

	for _, language := range languages {
		if _, ok := Resolve(language); !ok {
			t.Fatalf("Resolve(%q) reported unsupported language", language)
		}
	}
}

func TestNormalizeRunLangSupportsExtendedRuntimeSet(t *testing.T) {
	tests := map[string]string{
		"OCAML":       "ocaml",
		"ELIXIR":      "elixir",
		"FORTRAN":     "binary",
		"C3":          "c3",
		"D":           "binary",
		"COQ":         "rocq",
		"HASKELL":     "binary",
		"SML":         "binary",
		"LISP":        "lisp",
		"ASM":         "binary",
		"AHEUI":       "aheui",
		"NASM":        "binary",
		"ZIG":         "binary",
		"SWIFT":       "binary",
		"SQLITE":      "sqlite",
		"JULIA":       "julia",
		"ERLANG":      "erlang",
		"MERCURY":     "binary",
		"PROLOG":      "prolog",
		"R":           "r",
		"GROOVY":      "groovy",
		"SCALA":       "scala",
		"FSHARP":      "fsharp",
		"WASM":        "wasm",
		"BF":          "brainfuck",
		"WHITESPACE":  "whitespace",
		"SCHEME":      "scheme",
		"TCL":         "tcl",
		"GAWK":        "awk",
		"VB":          "vbnet",
		"LEAN":        "lean4",
		"TLAPLUS":     "tla",
		"WHYML":       "why3",
		"GST":         "smalltalk",
		"GNU_APL":     "apl",
		"VALA":        "binary",
		"HAXE":        "haxe",
		"KOTLIN/JAVA": "kotlin-jvm",
		"KOTLIN-JAVA": "kotlin-jvm",
		"RAKU":        "raku",
		"SED":         "sed",
		"BC":          "bc",
		"FORTH":       "forth",
		"GFORTH":      "forth",
	}

	for input, want := range tests {
		if got := NormalizeRunLang(input); got != want {
			t.Fatalf("NormalizeRunLang(%q) = %q, want %q", input, got, want)
		}
	}
}
