package limitdoc

import (
	"fmt"
	"strings"

	"aonohako/internal/api"
	"aonohako/internal/compile"
	"aonohako/internal/execute"
	"aonohako/internal/runvalidation"
)

func HumanBytes(value int) string {
	switch {
	case value%(1<<30) == 0:
		return fmt.Sprintf("%d GiB", value>>30)
	case value%(1<<20) == 0:
		return fmt.Sprintf("%d MiB", value>>20)
	case value%(1<<10) == 0:
		return fmt.Sprintf("%d KiB", value>>10)
	default:
		return fmt.Sprintf("%d bytes", value)
	}
}

func Markdown() string {
	var out strings.Builder
	out.WriteString("<!-- Code generated by `go run ./cmd/limitsdoc`; DO NOT EDIT. -->\n\n")
	out.WriteString("# Public request limits\n\n")
	out.WriteString("This table is generated from the constants enforced by the API, compile, and execute packages.\n\n")
	out.WriteString("| Contract | Default | Maximum |\n")
	out.WriteString("| --- | ---: | ---: |\n")
	fmt.Fprintf(&out, "| JSON request body | — | %s |\n", HumanBytes(api.MaxJSONBodyBytes))
	fmt.Fprintf(&out, "| Compile source files | — | %d files |\n", compile.MaxSourceFiles)
	fmt.Fprintf(&out, "| One decoded compile source | — | %s |\n", HumanBytes(compile.MaxDecodedSourceBytes))
	fmt.Fprintf(&out, "| Decoded compile source total | — | %s |\n", HumanBytes(compile.MaxDecodedSourceTotalBytes))
	fmt.Fprintf(&out, "| Compile stdout / stderr capture | — | %s each |\n", HumanBytes(compile.OutputCaptureBytes))
	fmt.Fprintf(&out, "| Execute binary files | — | %d files |\n", runvalidation.MaxBinaryFiles)
	fmt.Fprintf(&out, "| One decoded execute binary | — | %s |\n", HumanBytes(runvalidation.MaxBinaryFileBytes))
	fmt.Fprintf(&out, "| Decoded execute binary total | — | %s |\n", HumanBytes(runvalidation.MaxBinaryTotalBytes))
	fmt.Fprintf(&out, "| `stdin` / `expected_stdout` inline text | — | %s each |\n", HumanBytes(runvalidation.MaxTextFieldBytes))
	fmt.Fprintf(&out, "| Wall time | required | %d ms |\n", runvalidation.MaxTimeMs)
	fmt.Fprintf(&out, "| Memory | required | %d MiB |\n", runvalidation.MaxMemoryMB)
	fmt.Fprintf(&out, "| Stdout / stderr capture and response | %s | %s each |\n", HumanBytes(execute.DefaultOutputBytes), HumanBytes(runvalidation.MaxOutputBytes))
	fmt.Fprintf(&out, "| Workspace | %s | %s |\n", HumanBytes(execute.DefaultWorkspaceBytes), HumanBytes(runvalidation.MaxWorkspaceBytes))
	fmt.Fprintf(&out, "| Captured file output | — | %s |\n", HumanBytes(execute.MaxCapturedFileBytes))
	fmt.Fprintf(&out, "| Captured sidecar total | — | %s |\n", HumanBytes(execute.MaxCapturedSidecarTotalBytes))
	fmt.Fprintf(&out, "| Sidecar output paths | — | %d paths |\n", runvalidation.MaxSidecarOutputs)
	fmt.Fprintf(&out, "| Step programs | — | %d programs |\n", runvalidation.MaxPrograms)
	fmt.Fprintf(&out, "| Pipeline steps | — | %d steps |\n", runvalidation.MaxSteps)
	fmt.Fprintf(&out, "| Step stdin parts | — | %d parts |\n", runvalidation.MaxStdinParts)
	fmt.Fprintf(&out, "| Step handoff | — | %s |\n", HumanBytes(runvalidation.MaxStepHandoffBytes))
	return out.String()
}
